graph TD
    subgraph family ["FCA finds this family"]
        R["RLE Edema"]
        L["LLE Edema"]
        RU["RUE Edema"]
        LU["LUE Edema"]
        F["Facial Edema"]
        G["Generalized Edema"]
    end

    P["<b>Shared properties (the intent)</b><br/>assessment: edema<br/>val_type: custom_list<br/>value_domain: ordinal_severity"]

    R --- P
    L --- P
    RU --- P
    LU --- P
    F --- P
    G --- P
