#!/bin/bash
set -euo pipefail

# -------------------------------------------------------------------
# Scaffold a new CVB vocabulary project
#
# Usage:
#   ./scripts/new-vocab.sh VOCAB_NAME ID_BASE
#
# Example:
#   ./scripts/new-vocab.sh CARDIOLOGY 2082
#
# ID_BASE determines the concept ID ranges (all within [ID_BASE*1M, (ID_BASE+1)*1M)):
#   Standard IDs:      ID_BASE * 1_000_000            to  ID_BASE * 1_000_000 + 500_000
#   Non-standard IDs:  ID_BASE * 1_000_000 + 500_000  to  (ID_BASE + 1) * 1_000_000
#   Vocab concept ID:  ID_BASE * 1_000_000 + 499_999
#   Sequence start:    ID_BASE * 1_000_000 + 499_885
#
# Allocations are tracked in id-registry.csv at the repo root.
# This script checks for ID_BASE collisions and range overlaps before scaffolding.
# -------------------------------------------------------------------

if [[ $# -lt 2 ]]; then
    echo "Usage: $0 VOCAB_NAME ID_BASE"
    echo ""
    echo "  VOCAB_NAME  Name for the vocabulary (e.g., CARDIOLOGY)"
    echo "  ID_BASE     Numeric base for ID ranges (e.g., 2082)"
    echo ""
    echo "Existing allocations are tracked in id-registry.csv"
    exit 1
fi

VOCAB_NAME="$1"
ID_BASE="$2"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEMPLATE_DIR="${REPO_DIR}/_TEMPLATE"
TARGET_DIR="${REPO_DIR}/${VOCAB_NAME}"
REGISTRY="${REPO_DIR}/id-registry.csv"

# Validate
if [[ -d "${TARGET_DIR}" ]]; then
    echo "ERROR: Directory ${TARGET_DIR} already exists."
    exit 1
fi

if ! [[ "${ID_BASE}" =~ ^[0-9]+$ ]]; then
    echo "ERROR: ID_BASE must be a positive integer."
    exit 1
fi

# Compute ID ranges
# All IDs fit within [ID_BASE * 1M, (ID_BASE + 1) * 1M):
#   Standard:     ID_BASE * 1M       .. ID_BASE * 1M + 500K
#   Non-standard: ID_BASE * 1M + 500K .. (ID_BASE + 1) * 1M
ID_RANGE_MIN=$(( ID_BASE * 1000000 ))
ID_RANGE_MAX=$(( ID_RANGE_MIN + 500000 ))
ID_RANGE_START=$(( ID_RANGE_MAX - 115 ))
NS_RANGE_MIN="${ID_RANGE_MAX}"
NS_RANGE_MAX=$(( ID_RANGE_MIN + 1000000 ))
VOCAB_CONCEPT_ID=$(( ID_RANGE_MAX - 1 ))

VOCAB_LOWER=$(echo "${VOCAB_NAME}" | tr '[:upper:]' '[:lower:]')
DB_NAME="${VOCAB_LOWER}_vocabulary"

# Check id-registry.csv for collisions
if [[ -f "${REGISTRY}" ]]; then
    # Skip header line, check each existing allocation
    while IFS=, read -r reg_name reg_base reg_min reg_max reg_ns_min reg_ns_max _owner _date; do
        [[ "${reg_name}" == "vocab_name" ]] && continue  # skip header
        [[ "${reg_name}" == \#* ]] && continue           # skip comments
        [[ -z "${reg_base}" ]] && continue

        # Exact ID_BASE collision
        if [[ "${ID_BASE}" -eq "${reg_base}" ]]; then
            echo "ERROR: ID_BASE ${ID_BASE} is already allocated to ${reg_name}."
            echo "See id-registry.csv for existing allocations."
            exit 1
        fi

        # Vocab name collision
        if [[ "${VOCAB_NAME}" == "${reg_name}" ]]; then
            echo "ERROR: Vocabulary name ${VOCAB_NAME} already exists in id-registry.csv."
            exit 1
        fi

        # Range overlap: new [NS_RANGE_MIN, ID_RANGE_MAX] vs existing [reg_ns_min, reg_max]
        if [[ "${NS_RANGE_MIN}" -lt "${reg_max}" ]] && [[ "${ID_RANGE_MAX}" -gt "${reg_ns_min}" ]]; then
            echo "ERROR: ID range [${NS_RANGE_MIN}-${ID_RANGE_MAX}] overlaps with ${reg_name} [${reg_ns_min}-${reg_max}]."
            exit 1
        fi
    done < "${REGISTRY}"
fi

echo "=== Scaffolding ${VOCAB_NAME} ==="
echo ""
echo "  ID ranges:"
echo "    Standard:      ${ID_RANGE_MIN} - ${ID_RANGE_MAX}"
echo "    Non-standard:  ${NS_RANGE_MIN} - ${NS_RANGE_MAX}"
echo "    Sequence start: ${ID_RANGE_START}"
echo "    Vocab concept:  ${VOCAB_CONCEPT_ID}"
echo "  Database: ${DB_NAME}"
echo ""

# Copy template
echo "[1/4] Copying template..."
cp -r "${TEMPLATE_DIR}" "${TARGET_DIR}"

# Generate vocab.env
echo "[2/4] Generating vocab.env..."
cat > "${TARGET_DIR}/vocab.env" << EOF
## Vocabulary Configuration — ${VOCAB_NAME}
## Generated by scripts/new-vocab.sh on $(date +%Y-%m-%d)

VOCAB_NAME="${VOCAB_NAME}"
VOCAB_ID="${VOCAB_NAME}"
DB_NAME="${DB_NAME}"

ID_RANGE_MIN=${ID_RANGE_MIN}
ID_RANGE_MAX=${ID_RANGE_MAX}
ID_RANGE_START=${ID_RANGE_START}
NS_RANGE_MIN=${NS_RANGE_MIN}
NS_RANGE_MAX=${NS_RANGE_MAX}

VOCAB_CONCEPT_ID=${VOCAB_CONCEPT_ID}

MAPPING_FILES="mapping.csv"
STAGING_TABLES="temp.mapping"
EOF

# Update create-general-concepts.sql with actual values
echo "[3/4] Updating vocab-specific SQL..."
sed -i.bak \
    -e "s/2082499999/${VOCAB_CONCEPT_ID}/g" \
    -e "s/MY_VOCAB/${VOCAB_NAME}/g" \
    "${TARGET_DIR}/Builder/sql/create-general-concepts.sql"
rm -f "${TARGET_DIR}/Builder/sql/create-general-concepts.sql.bak"

# Update README
sed -i.bak \
    -e "s/MY_VOCAB/${VOCAB_NAME}/g" \
    "${TARGET_DIR}/README.md"
rm -f "${TARGET_DIR}/README.md.bak"

# Create the database (if Docker is running)
echo "[4/4] Creating database..."
if docker compose -f "${REPO_DIR}/docker-compose.yml" ps --services --filter "status=running" 2>/dev/null | grep -q db; then
    docker compose -f "${REPO_DIR}/docker-compose.yml" exec -T db \
        createdb -U postgres "${DB_NAME}" 2>/dev/null || echo "  Database ${DB_NAME} may already exist."
    # Initialize schema
    docker compose -f "${REPO_DIR}/docker-compose.yml" exec -T db \
        psql -U postgres -d "${DB_NAME}" -f /docker-entrypoint-initdb.d/01-create-vocab-schema.sql 2>/dev/null || true
    echo "  Database ${DB_NAME} created and schema initialized."
else
    echo "  Docker db service not running. Create the database manually:"
    echo "    docker compose up -d db"
    echo "    docker compose exec db createdb -U postgres ${DB_NAME}"
    echo "    docker compose exec db psql -U postgres -d ${DB_NAME} -f /docker-entrypoint-initdb.d/01-create-vocab-schema.sql"
fi

# Update id-registry.csv
if [[ -f "${REGISTRY}" ]]; then
    echo "${VOCAB_NAME},${ID_BASE},${ID_RANGE_MIN},${ID_RANGE_MAX},${NS_RANGE_MIN},${NS_RANGE_MAX},,$(date +%Y-%m-%d)" >> "${REGISTRY}"
    echo "  Updated id-registry.csv"
fi

echo ""
echo "=== ${VOCAB_NAME} scaffolded successfully ==="
echo ""
echo "Next steps:"
echo "  1. Edit ${VOCAB_NAME}/Builder/sql/create-general-concepts.sql"
echo "     - Verify vocabulary registration values"
echo "  2. Edit ${VOCAB_NAME}/Builder/sql/source-ddl.sql"
echo "     - Define staging table columns to match your CSV"
echo "  3. Edit ${VOCAB_NAME}/Builder/sql/load-source.sql"
echo "     - Map CSV columns to source_to_update"
echo "  4. Add mapping data to ${VOCAB_NAME}/Mappings/mapping.csv"
echo "  5. Run the pipeline:"
echo "     docker compose run runner ${VOCAB_NAME}/Builder/execute-pipeline.sh"
