#!/bin/bash
set -euo pipefail

# -------------------------------------------------------------------
# Scaffold a new CVB vocabulary project
#
# Usage:
#   ./scripts/new-vocab.sh VOCAB_NAME ID_BASE
#
# Example:
#   ./scripts/new-vocab.sh CARDIOLOGY 2082
#
# ID_BASE determines the concept ID ranges:
#   Standard IDs:      ID_BASE * 1_000_000       to  ID_BASE * 1_000_000 + 500_000
#   Non-standard IDs:  ID_BASE * 1_000_000 - 500_000  to  ID_BASE * 1_000_000
#   Vocab concept ID:  ID_BASE * 1_000_000 + 499_999
#   Sequence start:    ID_BASE * 1_000_000 + 499_885
#
# Existing ID_BASE allocations (do not reuse):
#   2062 = MIMIC
#   2072 = PSYCHIATRY
#   2076 = GIS
# -------------------------------------------------------------------

if [[ $# -lt 2 ]]; then
    echo "Usage: $0 VOCAB_NAME ID_BASE"
    echo ""
    echo "  VOCAB_NAME  Name for the vocabulary (e.g., CARDIOLOGY)"
    echo "  ID_BASE     Numeric base for ID ranges (e.g., 2082)"
    echo ""
    echo "Existing allocations: 2062 (MIMIC), 2072 (PSYCHIATRY), 2076 (GIS)"
    exit 1
fi

VOCAB_NAME="$1"
ID_BASE="$2"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEMPLATE_DIR="${REPO_DIR}/_TEMPLATE"
TARGET_DIR="${REPO_DIR}/${VOCAB_NAME}"

# Validate
if [[ -d "${TARGET_DIR}" ]]; then
    echo "ERROR: Directory ${TARGET_DIR} already exists."
    exit 1
fi

if ! [[ "${ID_BASE}" =~ ^[0-9]+$ ]]; then
    echo "ERROR: ID_BASE must be a positive integer."
    exit 1
fi

# Compute ID ranges
ID_RANGE_MIN=$(( ID_BASE * 1000000 ))
ID_RANGE_MAX=$(( ID_RANGE_MIN + 500000 ))
ID_RANGE_START=$(( ID_RANGE_MAX - 115 ))
NS_RANGE_MIN=$(( ID_RANGE_MIN - 500000 ))
NS_RANGE_MAX="${ID_RANGE_MIN}"
VOCAB_CONCEPT_ID=$(( ID_RANGE_MAX - 1 ))

VOCAB_LOWER=$(echo "${VOCAB_NAME}" | tr '[:upper:]' '[:lower:]')
DB_NAME="${VOCAB_LOWER}_vocabulary"

echo "=== Scaffolding ${VOCAB_NAME} ==="
echo ""
echo "  ID ranges:"
echo "    Standard:      ${ID_RANGE_MIN} - ${ID_RANGE_MAX}"
echo "    Non-standard:  ${NS_RANGE_MIN} - ${NS_RANGE_MAX}"
echo "    Sequence start: ${ID_RANGE_START}"
echo "    Vocab concept:  ${VOCAB_CONCEPT_ID}"
echo "  Database: ${DB_NAME}"
echo ""

# Copy template
echo "[1/4] Copying template..."
cp -r "${TEMPLATE_DIR}" "${TARGET_DIR}"

# Generate vocab.env
echo "[2/4] Generating vocab.env..."
cat > "${TARGET_DIR}/vocab.env" << EOF
## Vocabulary Configuration — ${VOCAB_NAME}
## Generated by scripts/new-vocab.sh on $(date +%Y-%m-%d)

VOCAB_NAME="${VOCAB_NAME}"
VOCAB_ID="${VOCAB_NAME}"
DB_NAME="${DB_NAME}"

ID_RANGE_MIN=${ID_RANGE_MIN}
ID_RANGE_MAX=${ID_RANGE_MAX}
ID_RANGE_START=${ID_RANGE_START}
NS_RANGE_MIN=${NS_RANGE_MIN}
NS_RANGE_MAX=${NS_RANGE_MAX}

VOCAB_CONCEPT_ID=${VOCAB_CONCEPT_ID}

MAPPING_FILES="mapping.csv"
STAGING_TABLES="temp.mapping"
EOF

# Update create-general-concepts.sql with actual values
echo "[3/4] Updating vocab-specific SQL..."
sed -i.bak \
    -e "s/2082499999/${VOCAB_CONCEPT_ID}/g" \
    -e "s/MY_VOCAB/${VOCAB_NAME}/g" \
    "${TARGET_DIR}/Builder/sql/create-general-concepts.sql"
rm -f "${TARGET_DIR}/Builder/sql/create-general-concepts.sql.bak"

# Update README
sed -i.bak \
    -e "s/MY_VOCAB/${VOCAB_NAME}/g" \
    "${TARGET_DIR}/README.md"
rm -f "${TARGET_DIR}/README.md.bak"

# Create the database (if Docker is running)
echo "[4/4] Creating database..."
if docker compose -f "${REPO_DIR}/docker-compose.yml" ps --services --filter "status=running" 2>/dev/null | grep -q db; then
    docker compose -f "${REPO_DIR}/docker-compose.yml" exec -T db \
        createdb -U postgres "${DB_NAME}" 2>/dev/null || echo "  Database ${DB_NAME} may already exist."
    # Initialize schema
    docker compose -f "${REPO_DIR}/docker-compose.yml" exec -T db \
        psql -U postgres -d "${DB_NAME}" -f /docker-entrypoint-initdb.d/01-create-vocab-schema.sql 2>/dev/null || true
    echo "  Database ${DB_NAME} created and schema initialized."
else
    echo "  Docker db service not running. Create the database manually:"
    echo "    docker compose up -d db"
    echo "    docker compose exec db createdb -U postgres ${DB_NAME}"
    echo "    docker compose exec db psql -U postgres -d ${DB_NAME} -f /docker-entrypoint-initdb.d/01-create-vocab-schema.sql"
fi

echo ""
echo "=== ${VOCAB_NAME} scaffolded successfully ==="
echo ""
echo "Next steps:"
echo "  1. Edit ${VOCAB_NAME}/Builder/sql/create-general-concepts.sql"
echo "     - Verify vocabulary registration values"
echo "  2. Edit ${VOCAB_NAME}/Builder/sql/source-ddl.sql"
echo "     - Define staging table columns to match your CSV"
echo "  3. Edit ${VOCAB_NAME}/Builder/sql/load-source.sql"
echo "     - Map CSV columns to source_to_update"
echo "  4. Add mapping data to ${VOCAB_NAME}/Mappings/mapping.csv"
echo "  5. Run the pipeline:"
echo "     docker compose run runner ${VOCAB_NAME}/Builder/execute-pipeline.sh"
